#!/bin/bash
# =============================================================================
# Samba AD DC provisioning entrypoint (fallback legacy trust core, §2.7).
# Idempotent: provisions once, persists to the volume, re-provisions on a
# clean-state reset (when the volume is dropped, §6).
# =============================================================================
set -euo pipefail

DOMAIN="${AD_DOMAIN:-STATEFED.LAB}"
REALM="${AD_REALM:-STATEFED.LAB}"
NETBIOS="${DOMAIN%%.*}"
ADMIN_PW="${AD_ADMIN_PASSWORD:-Sup3rS3cret-Admin!}"

SVC_ACCT="${AD_SVC_ACCOUNT:-svc_sql}"
SVC_PW="${AD_SVC_PASSWORD:-Summer2026}"
SVC_SPN="${AD_SVC_SPN:-MSSQLSvc/statedata.statefed.lab:1433}"

DCSYNC_ACCT="${AD_DCSYNC_ACCOUNT:-backup_admin}"
DCSYNC_PW="${AD_DCSYNC_PASSWORD:-Backup-Adm1n-2026}"

FLAG=/var/lib/samba/.provisioned
SAVED_CONF=/var/lib/samba/smb.conf.saved

if [ ! -f "$FLAG" ]; then
    echo "[samba-ad] provisioning domain $REALM (NetBIOS $NETBIOS)…"
    rm -f /etc/samba/smb.conf
    samba-tool domain provision \
        --use-rfc2307 \
        --realm="$REALM" \
        --domain="$NETBIOS" \
        --server-role=dc \
        --dns-backend=SAMBA_INTERNAL \
        --adminpass="$ADMIN_PW"

    # ---- Kerberoastable service account (SPN + weak password) — T1558 --------
    echo "[samba-ad] creating kerberoastable service account: $SVC_ACCT"
    samba-tool user create "$SVC_ACCT" "$SVC_PW"
    samba-tool user setexpiry "$SVC_ACCT" --noexpiry
    samba-tool spn add "$SVC_SPN" "$SVC_ACCT"

    # ---- DCSync-capable privileged account — T1003.006 / T1110 --------------
    echo "[samba-ad] creating DCSync-capable account: $DCSYNC_ACCT"
    samba-tool user create "$DCSYNC_ACCT" "$DCSYNC_PW"
    samba-tool user setexpiry "$DCSYNC_ACCT" --noexpiry
    samba-tool group addmembers "Domain Admins" "$DCSYNC_ACCT"

    cp /etc/samba/smb.conf "$SAVED_CONF"
    touch "$FLAG"
    echo "[samba-ad] provisioning complete."
else
    echo "[samba-ad] already provisioned — restoring config."
    cp "$SAVED_CONF" /etc/samba/smb.conf
fi

# Kerberos client config generated by the provision step.
cp -f /var/lib/samba/private/krb5.conf /etc/krb5.conf || true

echo "[samba-ad] starting Samba AD DC in foreground…"
exec samba --foreground --no-process-group
